// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver'
import chai from 'chai'
const expect = chai.expect

describe('a memory game', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('unmaching pairs', async function() {
    await driver.get("http://127.0.0.1:5500/src/memory.html")
    await driver.manage().window().setRect({ width: 1440, height: 900 })
    const card1 = await driver.findElement(By.id("row_0-col_0"))
    expect(await card1.getAttribute('src')).to.equal('http://127.0.0.1:5500/src/images/dos.jpeg')
    card1.click()
    expect(await card1.getAttribute('src')).to.not.equal('http://127.0.0.1:5500/src/images/dos.jpeg')
    const card2 = await driver.findElement(By.id("row_2-col_2"))
    card2.click()
    expect(await card2.getAttribute('src')).to.not.equal('http://127.0.0.1:5500/src/images/dos.jpeg')
    this.timeout(2000)
    expect(await card1.getAttribute('src')).to.not.equal('http://127.0.0.1:5500/src/images/dos.jpeg')
    expect(await card2.getAttribute('src')).to.not.equal('http://127.0.0.1:5500/src/images/dos.jpeg')
  })
})
